// <auto-generated />
namespace ShadrackPhoneRepair.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditWalkinRequestModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditWalkinRequestModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202011191324346_EditWalkinRequestModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
